version: '3'
services:
    db:
        container_name: postgres_instance
        image: postgres:13.0-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env

    app:
        build: .
        container_name: flask_app
        ports:
            - 5000:5000
        depends_on:
            - db
        env_file:
            - .env

volumes:
  pgdata: {}